### ISSUE TITLE
[Windows] Error msi bundle

### ISSUE THREAD

**Issue by mrdev023** [burtonageo/cargo-bundle#77]
I get this error

error: Failed to collect resource file information
  Caused by: Le fichier spécifié est introuvable. (os error 2)

**Comment by jojobyte** [comment]
jojobyte/cargo-bundle@ca33209

First time working working with Rust, there is no way this is the **right** solution for cross platform. 

The error appears to be because its trying to bundle `C:/whatever/your/path/hello` instead of  `C:/whatever/your/path/hello.exe`, fixing it inside the collect_resource_info function just gets it to fail later on inside the generate_resource_cabinets function. 

Fixing it in settings solves both problems but then generates a MSI file that won't run/install, but someone else might need to figure out that part. 

Think it needs some MSI tables/registry or something but its beyond my current understanding.

**Comment by slonopotamus** [comment]
As a workaround, you may try using [cargo-wix](https://github.com/volks73/cargo-wix) instead.

**Comment by lobis** [comment]
I just found this project but I could not get the provided example to work on windows either due to this same error. Is there any plans fix this in the near future? Thanks!

**Comment by mdsteele** [comment]
Windows support in cargo-bundle is only half-implemented and doesn't work yet.  It is waiting for a contributor who knows more about MSI packaging than I do and who has a Windows machine to test on.  If that's you, PRs would be very welcome!

**Comment by JessicaTegner** [comment]
hi @aerkiaga 

THat's really great! I would say a minimal UI as well. You might want to read #116  as there has been a long discussion there as well about MSI support

**Comment by mdsteele** [comment]
@aerkiaga This is great news, thanks!  A working UI would definitely be good to have, although if it makes sense to split it across multiple smaller PRs, that may be a little easier to review.  Up to you.

**Comment by landonwork** [comment]
How is this coming along? I'm new to Windows MSI files and bundlers, but if there isn't much left to be done, I would be willing to take a stab.

**Comment by aerkiaga** [comment]
@landonwork I got basic msi working with https://github.com/burtonageo/cargo-bundle/pull/142, which has been merged. It lacks some features though. I've drawn a banner for the installer UI [here](https://github.com/aerkiaga/cargo-bundle/tree/msi-banner) if you need it.

**Comment by Plycedes** [comment]
I get the same error. Is it solved yet??

**Comment by mdsteele** [comment]
To clarify, are you having issues with `cargo-bundle` as built at HEAD, or using the version published on crates.io?

**Comment by Alexangelj** [comment]
> To clarify, are you having issues with `cargo-bundle` as built at HEAD, or using the version published on crates.io?

I cloned from commit `fd94ab531b4d7b0c9a8f029dd649156f0e733157`, (latest master branch as of Jan 29, 24) and installed directly. I still get the error with running `cargo bundle --target x86_64-pc-windows-msvc`. I am only using the required configs - I'm on windows 11

**Comment by jakobhansson** [comment]
Same problem here, with `cargo-bundle 0.6.0`

**Comment by aerkiaga** [comment]
@jakobhansson I see the fix has not yet made it into a new release. I suggest that you build from source (`cargo install --path .` from `cargo-bundle` master branch).

**Comment by jakobhansson** [comment]
the `cargo bundle --format msi` command completes successfully, but the generated .msi file throws error upon running "This installation packaeg could not be opened..."

**Comment by AardhynLavender** [comment]
Same issues here...

The *crates.io* version fails to bundle with a "Failed to collect resource file information" error when running `cargo bundle --format msi`.

Building from source (cloning and running `cargo install --path .`) succeeds and produces a `.msi` file but Windows Installer throws "This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package" when I try to open it.

**Comment by egeres** [comment]
I'm having this issue with: `cargo-bundle v0.6.1`, I'm not sure what to do

**Comment by fredclausen** [comment]
Same here with the issue on `v0.6.1`.

**Comment by poly2it** [comment]
This issue doesn't occur for me if I run the command with the following format:
```
$ cargo bundle --target x86_64-pc-windows-msvc --format msi --release
   Compiling x v0.1.0 (/home/bach/projects/x)
    Finished `release` profile [optimized] target(s) in 2.26s
warning: MSI bundle support is still experimental.
    Bundling x.msi
    Finished 1 bundle at:
        /home/bach/projects/x/target/x86_64-pc-windows-msvc/release/bundle/msi/x.msi
```

**Comment by poly2it** [comment]
However, the "This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package" issue is still present.

Trying to open the generated MSI file on [an MSI reader](https://pymsi.readthedocs.io/en/latest/msi_viewer.html) backed by the same MSI crate, I get this error:
```
Error processing MSI file: Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 3, in <module> File "/lib/python3.11/site-packages/pymsi/package.py", line 33, in __init__ self._load() File "/lib/python3.11/site-packages/pymsi/package.py", line 39, in _load self.summary = Summary(stream) ^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/pymsi/summary.py", line 21, in __init__ self.properties = PropertySet(stream) ^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/pymsi/propset.py", line 53, in __init__ self.codepage = CodePage(value.value) ^^^^^^^^^^^^^^^^^^^^^ File "/lib/python3.11/site-packages/pymsi/codepage.py", line 37, in __init__ raise ValueError(f"Unsupported code page ID: {id}") ValueError: Unsupported code page ID: -535 
```

**Comment by aerkiaga** [comment]
@poly2it -535 as a 16-bit signed value just happens to have the same representation as unsigned 65001, which is the code page for UTF-8; the `msi` crate sets that code page by default. Might be a bug in `pymsi` rather than `cargo-bundle`, but I suppose [this method](https://docs.rs/msi/latest/msi/struct.Package.html#method.set_database_codepage) could be used to test whether changing the code page fixes this issue. Unfortunately, I can only test on Wine, so I can't reproduce this issue (works fine there).
